name: AxShulkers
version: '${project.version}'
main: com.artillexstudios.axshulkers.AxShulkers
api-version: '1.13'
folia-supported: true

commands:
  axshulkers:
    usage: /<command>
    aliases:
      - axshulker

permissions:
  axshulkers.reload:
    default: op
  axshulkers.clear:
    default: op
  axshulkers.modify:
    default: true
  axshulkers.use:
    default: true